language: node_js
node_js:
  - 14
  - node
install:
  - npm install
branches:
  only:
    - main
script: 'true'
deploy:
  provider: heroku
  api_key: 
    secure: $HEROKU_API_KEY
  app: 'js-project-87'
  on: 
    branch: main
